name: "Build and deploy artifact"
on:
  push:
    branches:
      - "master"
env:
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
  MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code from github
          uses: actions/checkout@v3

        - name: Set up Java JDK
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'adopt'
            server-id: ossrh
            server-username: MAVEN_USERNAME
            server-password: MAVEN_PASSWORD
            gpg-private-key: MAVEN_GPG_PRIVATE_KEY
            gpg-passphrase: MAVEN_GPG_PASSPHRASE

        - name: Build the artifact
          run: mvn clean deploy

        - name: Deploy the artifact
          run: mvn nexus-staging:release

